# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poke_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokeowner', to='docker.Users')),
                ('poked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ispoked', to='docker.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='quote_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
