# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0002_auto_20170130_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
